<PreviewPane>:
    line_color: app.gray_100
    radius: dp(16)
    line_width: dp(2)

    canvas:
        Color:
            rgba: app.gray_100
        SmoothEllipse:
            size: dp(16), dp(16)
            pos: self.x + dp(16), self.top - dp(32)

        Color:
            rgba: [0, 0, 0, 0.5]
        SmoothRoundedRectangle:
            size: dp(100), dp(4)
            pos: self.center_x - dp(50), self.y + dp(12)
            radius: [dp(2)]